# Generated by Django 5.2.6 on 2025-09-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_is_paid_alter_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
