# Generated by Django 5.2.6 on 2025-09-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Yet to be Delivered", "Yet to be Delivered"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Yet to be Delivered",
                max_length=20,
            ),
        ),
    ]
