# Generated by Django 5.2.6 on 2025-09-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(default=12, max_length=500),
            preserve_default=False,
        ),
    ]
